# Generated by Django 4.1.3 on 2022-11-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='average_review_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='introduction_brief',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='num_of_enrolled_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='num_of_published_course',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='num_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='num_of_course_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='num_of_course_enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
